version: '3.4'

services:
  trafficdb:
   container_name: trafficdb
   restart: always
   ports:
      - "27017:27017"
   volumes:
     - mongo_data:/data/db

  portainer:
    container_name: portainer
    restart: always
    ports:
       - "8080:8000"
       - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  trafficticket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://trafficdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - trafficdb
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro